_target_: train.datamodules.language_modeling_hf.LMDataModule
dataset_name: DKYoon/SlimPajama-6B
dataset_config_name: default
tokenizer_name: gpt2
cache_dir: ${oc.env:DATA_DIR,${data_dir}}/SlimPajama-6B/cache
max_length: 2048
add_eos: True
batch_size: 4  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 64  # For preprocessing only
use_shmem: False
shuffle: True
pin_memory: True
__train_len: ${div_up:23997342716, ${.max_length}}
